##GETTING STUDENT TOKEN
##GET https://users-dasw.herokuapp.com/api/tokenDASW
##x-expediente: 709385


##REGISTERING USER
##POST https://users-dasw.herokuapp.com/api/users/
##Content-Type: application/json
#x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBlZGllbnRlIjoiNzA5Mzg1IiwiaWF0IjoxNTcyMjcxMTAwfQ.Ifaroy08WSikYjZuiKfC-vAVj8s2VF5iXdZR1FCXKhw

#{
#  "nombre":"Li",
  #"apellido":"G",
  #"correo":"t123@t.com",
  #"url":"",
  #"sexo":"H",
  #"fecha":"10-10-2019",
  #"password":"12345"
#}

##Login
#POST https://users-dasw.herokuapp.com/api/login
#Content-Type: application/json
#x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBlZGllbnRlIjoiNzA5Mzg1IiwiaWF0IjoxNTcyMjcxMTAwfQ.Ifaroy08WSikYjZuiKfC-vAVj8s2VF5iXdZR1FCXKhw

#{
#  "correo": "c@c.com",
#  "password": "123"
#}


# ##Delete
DELETE https://users-dasw.herokuapp.com/api/users/c@c.com
Content-Type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBlZGllbnRlIjoiNzA5Mzg1IiwiaWF0IjoxNTcyMjcxMTAwfQ.Ifaroy08WSikYjZuiKfC-vAVj8s2VF5iXdZR1FCXKhw
x-user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBlZGllbnRlIjoiNzA5Mzg1IiwiY29ycmVvIjoiY0BjLmNvbSIsImlpZCI6NCwiaWF0IjoxNTczMjYwNjk3LCJleHAiOjE1NzMyNjQyOTd9.RelJJEgC1u5OjyLDqF1sd4NaNC-w755aq4i1Yh1jF6I



##
#{
  #"tokenAlumno": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBlZGllbnRlIjoiNzA5Mzg1IiwiaWF0IjoxNTcyMjcxMTAwfQ.Ifaroy08WSikYjZuiKfC-vAVj8s2VF5iXdZR1FCXKhw"
#}


  ##"tokenUsuario": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBlZGllbnRlIjoiNzA5Mzg1IiwiY29ycmVvIjoiY0BjLmNvbSIsImlpZCI6NCwiaWF0IjoxNTczMjYwNjk3LCJleHAiOjE1NzMyNjQyOTd9.RelJJEgC1u5OjyLDqF1sd4NaNC-w755aq4i1Yh1jF6I"
